services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - micro

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - micro
  shuffle:
    image: "micra1/service-shuffle:v1"
    container_name: "shuffle-ms"
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - micro
    environment:
      KAFKA_BROKERS: "kafka:9092"
  log:
    image: "micra1/service-log:v1"
    container_name: "log-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - micro
    environment:
      KAFKA_BROKERS: "kafka:9092"

networks:
  micro:
    driver: bridge